site_name: John Telford

theme:

  name: material

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.tracking
    - toc.follow
    - header.autoide

  palette:

    primary: teal
    accent: indigo
 
  features:
    - navigation.tracking
    - navigation.instant
    # - navigation.indexes
    - toc.follow
    # - navigation.tabs

# nav tree
nav:
#
  - Home:
    - Iterative website development: index.md

  - Teams:
    - Teams Overview: team_overview.md
    - Define Team: team_define.md
    - Design Team: team_design.md
    - Development Team:
      - Website Development: team_develop.md
      - Development Stack:
        - Dev Stack Overview: website_dev_stack.md
        - Dev Stack Details: dev_stack_details.md
      - Development Tools: development_tools.md
      - Programming: programming.md
      - Workstations: workstations.md
    - Deploy Team: team_deploy.md
    - Maintenance Team: team_maintenance.md


  - Technology: 
    - Technology Guide: technology_guide.md

    - Version Control System: technology_guide/#version-control-system
    - Git GitHub Getting Started: technology_guide/#git-github-getting-started
    - GitHub: technology_guide/#github/
    - Git: technology_guide/#git/

    - Website Development:
      - MkDocs: technology_guide/#mkdocs
      - Materials for MkDocs: technology_guide/#materials-for-mkdocs

  - Site Notes: 
    - Remediation: remediation.md
    - Glossary: glossary.md

  - Hype:
    - Hype Curve: hype_curve.md
    - Hype Guesstimates: hype_guesstimates.md

#       - Development Tools:
#         # - developmenttools.md
#         - vscode.md

#       - Programming:  
#         - programming.md

#       - workstations.md
#       - material.md

#   - Company:
#     - About: company.md
#     - Contact: contact.md

#   - Materials for MkDocs:
#     - creating site.md
#     - diagrams.md

markdown_extensions:
  - admonition
  
  - pymdownx.details
  
  - pymdownx.extra
  - attr_list
  - md_in_html

  - toc:
      permalink: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2022 John Telford


site_url: https://localhost:8000

