site_name: John Telford

theme:

  name: material

  font: light 300
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.tracking
    - toc.follow

  palette:

    primary: teal
    accent: indigo
 
  features:
    - navigation.tracking
    - navigation.instant
    # - navigation.indexes
    - toc.follow
    # - navigation.tabs

# nav tree
nav:
#   - Home: index.md
#   - Overview: siteoverview.md

  - Project Teams:
    - Teams Overview: teams.md
    - Define Team: team_define.md
    - Design Team: team_design.md

  - Team Develop:
    - Website Development: team_develop.md
    - Website Development Stack: website_dev_stack.md
    - Programming: programming.md
    - Workstations: workstations.md

#       - Development Tools:
#         # - developmenttools.md
#         - vscode.md

#       - Programming:  
#         - programming.md

#       - workstations.md
#       - material.md

#   - Company:
#     - About: company.md
#     - Contact: contact.md

#   - Materials for MkDocs:
#     - creating site.md
#     - diagrams.md

markdown_extensions:
  - admonition
  
  - pymdownx.details
  
  - pymdownx.extra
  - attr_list
  - md_in_html

  - toc:
      permalink: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2022 John Telford


site_url: https://localhost:8000

